packages:
  - 'packages/*'
  - 'packages/*/*'
  - 'examples/*'
catalog:
  '@antfu/eslint-config': ^3.12.0
  '@types/node': ^22.10.2
  eslint: ^9.16.0
  rimraf: ^6.0.1
  typescript: ^5.7.2
  unbuild: ^3.1.0
  vitest: ^2.1.8
  consola: ^3.3.3
  jsdom: ^25.0.1
